### ISSUE TITLE
Containers are stopped immediately after run

### ISSUE THREAD

**Issue by OnkelTem** [dnephin/dobi#101]
Why does it stop my project immediately?

dobi.yaml:
```yaml
compose=dev:
  files: [docker-compose.yml, docker-compose.override.yml]
  project: '{env.PROJECT}'
```
```
[local]$ dobi dev
[WARN] meta.project is not set. Using default "docker".
[compose:up dev] docker-compose.yml,docker-compose.override.yml project up
Creating myproject_db_1 ...
Creating myproject_mail_1 ...
Creating myproject_mail_1
Creating myproject_db_1 ... done
Creating myproject_web_1 ...
Creating myproject_web_1 ... done
[compose:up dev] docker-compose.yml,docker-compose.override.yml Done
[compose:up dev] docker-compose.yml,docker-compose.override.yml project stop
Stopping myproject_web_1  ... done
Stopping myproject_db_1   ... done
Stopping myproject_mail_1 ... done
[compose:up dev] docker-compose.yml,docker-compose.override.yml Done
```
