### ISSUE TITLE
[ERROR] failed to load config from "dobi.yaml": duplicate resource name <..>

### ISSUE THREAD

**Issue by OnkelTem** [dnephin/dobi#109]
When I try to use one name for different records I get an error message like this:

`[ERROR] failed to load config from "dobi.yaml": duplicate resource name <..>`

So let's put I have an image called `myimage` and I just want to run it. This is a `dobi.yaml` which comes to my mind first:

```yaml
image=myimage:
    image: myimage
    tags: ['mytag']
    context: images/myimage
    dockerfile: Dockerfile

job=myimage:
    use: myimage
    command: /entrypoint.sh
```

But this is not allowed, as I can't use "myimage" twice. So I have to rename them but since I don't have any new names in my mind (I don't have any new entities except of those I've already mentioned!) I have to conjure up some new names inevitably running into the naming problem: 

```yaml
image=myimage-image:
    image: myimage
    tags: ['mytag']
    context: images/myimage
    dockerfile: Dockerfile

job=myimage:
    use: myimage-image
    command: /entrypoint.sh
```

which looks pretty bogus, since: 
1) I had to add `-image` suffix while I already had `image=` prefix.
2) In the second line I say one more time: `image: myimage`.
3) In the job specs I have to use `myimage-image` to reference image which doesn't even *look* like my original image which name was `myimage`.

As for (2) - it's inevitable  I understand, but other two are the result of that uniqueness requirement. So why require uniqueness of keys after all? It doesn't make much sense for me. Just make `type=name` unique, not just `name`.
