### ISSUE TITLE
Run a container which is used by another container

### ISSUE THREAD

**Issue by OnkelTem** [dnephin/dobi#114]
Being familiar with Dobi for about a month I haven't yet used it anywhere (despite I have lots of different setups), because whenever I try it - I either can't find the appropriate example or I can't really get the concepts behind it, and so I have to fallback to docker-compose every time. At that, I feel like Dobi is much more interesting for me then docker-compose. :) Ok, so here is a new attempt to start with Dobi.

I have three services: 
- 1st **service-provider** - is a service process which is assumed to run forever
- 2nd **service-configurator** - is a task process which configures the 1st one and then exits
- 3rd **project**  is a composer process which runs several containers which can use the 1st process.

So this is my dobi.yaml (which doesn't work):

```
mount=dir:
  bind: .
  path: /dir

image=service-provider-image:
  image: service-provider

image=service-configurator-image:
  image: service-configurator

job=run-service-provider:
  use: service-provider-image:
  mounts: [dir]

job=run-service-configurator:
  use: service-configurator-image
  mounts: [dir]
  depends: [run-service-provider]
  interactive: true

composer=project
  depends: [run-service-configurator]
  files: [docker-compose.yml, docker-compose.override.yml]
```

What I expect from it is when I run e.g. `dobi project:detach` it would:
1) run `run-service-provider` task which starts up the service and goes into background
2) run `run-service-configurator` task which configures the previous service and exists
3) run `project` composer task which startups the project

Currently it just stops on the first service - `run-service-provider`.

Any clue how can I use it?

**Comment by dnephin** [comment]
Yup, this is something that is unfortunately still missing. `job=run-service-provider` would need to be something like `service=run-service-provider` using #45. 

The only workaround is to use `compose=run-service-provider` and have a small compose file that runs the image.

You'll also need to add `net-mode: projectname_default` to `job=run-service-configurator` so that it can communicate with the service started by `compose=run-service-provider`. This is also something that i'd like to make more automatic, but I haven't found a good way to express it yet.

**Comment by OnkelTem** [comment]
Thanks for the advice. Let me try, I'll write back.

**Comment by OnkelTem** [comment]
Let me switch now to some real examples:

- `service-provider` starts `ssh-agent`
- `service-configurator` adds ssh keys via `ssh-add`
- `project` is the same as above but it also a client of `ssh-agent`

They don't need some network for communication as they simply share the same `SSH_AUTH_SOCK` path.

This is my **dobi.yaml** file (slightly edited):

```
mount=home_ssh:
  bind: ~/.ssh
  path: /home/user/.ssh

mount=ssh_sock:
  name: ssh_sock
  path: /ssh

image=ssh:
  image: image
  context: images/ssh

compose=ssh-agent:
  files: [docker-compose.ssh.yml]
  project: '{env.PROJECT}'

job=add-keys:
  use: ssh
  mounts: [ssh_sock, home_ssh]
  depends: ['ssh-agent:detach']
  interactive: true
  env:
    - APP_UID={env.UID}
    - RUN_AS_USER=1
    - KEYS=id_dsa
  command: /ssh-add-keys.sh
```

**docker-compose.ssh.yml**:

```
version: "3.2"
services:
  ssh:
    build:
      context: images/ssh
    volumes:
      - ssh:/ssh
    environment:
      APP_UID: ${UID}
      RUN_AS_USER: 1
    command: /ssh-agent.sh
volumes:
  ssh:
```

Now `dobi ssh-agent:detach` - starts up a container.
But `dobi add-keys` - doesn't work: it can't connect to ssh-agent. 
However, it works fine when I start it like this: `docker-compose -p project -f docker-compose.add-keys.yml run add-keys` where `docker-compose.add-keys.yml` is a file similar to `docker-compose.ssh.yml` - it only redefines the command and adds environment variable KEYS:

```
version: "3.2"
services:
  add-keys:
    build:
      context: images/ssh
    volumes:
      - ssh:/ssh
      - ~/.ssh:/home/user/.ssh
    environment:
      APP_UID: ${UID}
      RUN_AS_USER: 1
      KEYS: id_dsa id_rsa_4096
    command: /ssh-add-keys.sh
volumes:
  ssh:
```

It's hard for to tell what happens exactly, but it could be that volume 'ssh' is not share between compose'd container (ssh-agent) and dobi's container (add-keys).

**Comment by OnkelTem** [comment]
Just to bring the matter to the end, I decided to eliminate possible volume naming problem.

So this is my **dobi.yaml**:

```
meta:
  project: project

mount=home_ssh:
  bind: ~/.ssh
  path: /home/user/.ssh

mount=ssh_sock:
  name: '{env.PROJECT}_ssh'
  path: /ssh

image=ssh:
  image: image
  context: images/ssh

compose=ssh-agent:
  files: [docker-compose.ssh.yml]
  project: '{env.PROJECT}'

job=add-keys:
  use: ssh
  mounts: [ssh_sock, home_ssh]
  depends: ['ssh-agent:detach']
  interactive: true
  # net-mode: projectname_default
  env:
    - APP_UID={env.UID}
    - RUN_AS_USER=1
    - KEYS=id_dsa id_rsa_4096
  command: /ssh-add-keys.sh

```

Note that I had to prefix the `name` of the `mount=ssh_sock` with `{env.PROJECT}` name. Now when I run: `PROJECT=bb8 dobi add-keys` it outputs like:
 
[local]$ dobi add-keys
[image:build ssh] image is fresh
[compose:detach ssh-agent] docker-compose.ssh.yml project up
Creating network "bb8_default" with the default driver
Creating volume "bb8_ssh" with default driver
Creating bb8_ssh_1 ...
Creating bb8_ssh_1 ... done
[compose:detach ssh-agent] docker-compose.ssh.yml Done
[mount: ssh_sock] :/ssh Created
[job: add-keys] /ssh-add-keys.sh Start
Enter passphrase for /home/user/.ssh/id_dsa:
Identity added: /home/user/.ssh/id_dsa (/home/user/.ssh/id_dsa)
Identity added: /home/user/.ssh/id_rsa_4096 (/home/user/.ssh/id_rsa_4096)
[job: add-keys] /ssh-add-keys.sh Done
```

and `bb8_ssh_1` container seems to be running still, so I think it would work when I start up my main project. 

I must say that the same result I can achieve with one docker-compose.yml, joining all the stuff in the same file:

```
version: "3.2"

services:

  ssh:
    build:
      context: images/ssh
    volumes:
      - ssh:/ssh
    environment:
      APP_UID: ${UID}
      RUN_AS_USER: 1
    command: /ssh-agent.sh

  add-keys:
    build:
      context: images/ssh
    volumes:
      - ssh:/ssh
      - ~/.ssh:/home/user/.ssh
    stdin_open: true
    tty: true
    environment:
      KEYS: id_dsa id_rsa_4096
      APP_UID: ${UID}
      RUN_AS_USER: 1
    depends_on:
      - ssh
    command: /ssh-add-keys.sh

  web:
   # ...

  db:
   # ...

  mail:
   # ...

volumes:
  ssh:
  db:
```

running one command to initialize ssh-agent and add the keys:
```
docker-compose -p bb8 run add-keys
```
and another one to start the project:
```
docker-compose -p bb8 up web
```
