### ISSUE TITLE
How can I make env variables available to the `image` task?

### ISSUE THREAD

**Issue by Fuco1** [dnephin/dobi#144]
I want to tag the image based on some env variable, but there is no way to specify those for the `image` task.  Also the build args often come from environment, for example 

    docker build --build-arg=NPM_TOKEN

will take the value from the environment.  I don't see a way to do this currently.

I'm trying to model this `docker build` line as a task

    docker build --build-arg=NPM_TOKEN -t "$IMAGE_DEPS_DEV" -f Dockerfile.deps.dev .

**Comment by Enteee** [comment]
The `image` task does suppor a `tags` parameter [1] which do support configuration variables. Using configuration variables you can access envrionment. 

I configure image resources like this:
```
image=image/A
  tags: [
    "{env.TAG}"
   ]
   args:
     NPM_TOKEN: "{env.NPM_TOKEN}"
   ...
``

does this help?

[1]: https://dnephin.github.io/dobi/config.html#image

**Comment by dnephin** [comment]
@Enteee example is exactly right for handling build args, and setting the image tag.

@Fuco1 the image name is separate from the "resource name". You can use environment variable in the image name as well, but you always refer to the image resource using the resource name. Example:

```yaml
image=TheResourceName:
  image: "{env.SOME_VAR}"

job=something:
  use: TheResourceName
```

So in your case the config might look something like this:

```yaml
image=deps-dev:
  image: "{env.IMAGE_DEPS_DEV}"
  args: ["NPM_TOKEN={env.NPM_TOKEN"]
```

However if `IMAGE_DEPS_DEV` contains both the name and the tag you will need to split that up into two environment variables, so you can set image name and tags separately.
