### ISSUE TITLE
Only one tag is applied on image:build

### ISSUE THREAD

**Issue by Fuco1** [dnephin/dobi#148]
When I have two tags in an image task

```
image=deps-prod:
  image: image
  pull: always
  tags:
    - "{env.LOCKFILE_HASH}-prod"
    - prod-build
  dockerfile: Dockerfile.deps.prod
  depends:
    - "compute-lockfile-hash:capture(LOCKFILE_HASH)"
    - base-dev
  args:
    NPM_TOKEN: "{env.NPM_TOKEN}"
```

only the first one is applied during the build.  I need both tags to be applied because currently `COPY --from=...` does not support build args and so I have to have a static name also.
