### ISSUE TITLE
Add feature to expand environmental variables defaults to actual values of those defaults

### ISSUE THREAD

**Issue by uzakoff** [dnephin/dobi#156]
In the documentation: [https://dnephin.github.io/dobi/variables.html](https://dnephin.github.io/dobi/variables.html) it says that variables can have default values. When I am building an image I would like dobi to resolve those defaults to their actual value. For example if I run `b=1 dobi image/test` I would like `RUN echo ${evaluate}` to print 1 instead of env.b, which is what happens now.

Dockerfile
```
FROM   alpine:3.4
ARG evaluate
RUN echo ${evaluate}  
```

dobi.yaml
```
image=image/test:
  image: myproject
  dockerfile: Dockerfile
  args:
     evaluate: "{env.a:env.b}"
```
