### ISSUE TITLE
config variables not expanded in cache-from

### ISSUE THREAD

**Issue by Fuco1** [dnephin/dobi#163]
It seems like the config variables are not expanded in cache-from

```yaml
meta:
  project: project

image=server:
  image: {project}
  pull-base-image-on-build: false
  target: server
  cache-from:
    - {project}:latest   ##### <==== seems to have no effect, cache is never used.
  context: .
  tags:
    - latest
```

When I replace `{project}` with `project` (the expansion) manually dobi uses cache for build.
