### ISSUE TITLE
Can we compute env in shell

### ISSUE THREAD

**Issue by kindritskyiMax** [dnephin/dobi#173]
I am asking about the ability to compute env vars before command run. This is kinda `makefile` behavior.

For example, calculate a hash from the file, and expose it as `MY_TAG` and use it as a tag for the image.

`cat myfile.txt | base64 -`

I have 
```sh
image=myimage:
    tags: ['{env.MY_TAG}']
``` 
I would like to note that it would be great to do it in `dobi` and not outside of it

For example this is not desired:

```
MY_TAG=$(cat myfile.txt | base64 -) dob myimage:pull
```

**Comment by dnephin** [comment]
Yes, this is supported using the `:capture()` task of a job resource: http://dnephin.github.io/dobi/tasks.html#job-tasks

There is an example here: https://github.com/dnephin/dobi/blob/master/examples/env-vars/dobi.yaml

I think for your case it would be something like this:

```yaml

image=bash:
  image: bash
  tags: [5]
  pull: once

job=base64:
  use: bash
  command: bash -c 'cat myfile.txt | base64 -'

image=myimage:
  tags: ['{env.MY_TAG}']
  depends:
    - base64:capture(MY_TAG)
```
