### ISSUE TITLE
Proposal: CI friendly tracking

### ISSUE THREAD

**Issue by tduffield** [dnephin/dobi#182]
This is a proposal for functionality that I'm needing to write. The only question is whether or not you would like to accept it in the upstream. 

The crux of my issue is that I want to use dobi in my CI environment to build Docker images. I need to optimize for parallelization, so I'm using the `depends` Image config to build a DAG which I can use to run builds in parallel. However, there are two issues that I'm running into with running dobi in CI, both of which revolve around the fact that I don't have a persistent host. 

1) My git clone does not preserve the original modification times
2) I can't rely on the `.dobi` directory to keep track of my records. 

My solution to this problem is to expand the existing functionality, which I refer to as `file-mtime`. Instead of looking at the mtime of the context directory, I would look at the timestamp of my HEAD commit. And instead of relying on the mtime of the record file, I would write the `LastBuild` timestamp into the record itself. 

I would use S3 to store the record files, syncing them to/from my hosts as necessary. 

I figure that this behavior could be controlled by meta parameters like so: 

```
meta:
    project: git-file-inline
    tracking:
      change: git           # options: file-mtime (default), git
      record: file-inline   # options: file-mtime (default), file-inline
```

Thoughts? Questions? Concerns?
