### ISSUE TITLE
Feature: allow for inclusion of subproject/dobi.yaml

### ISSUE THREAD

**Issue by dnephin** [dnephin/dobi#22]
`dobi.yaml` allows for includes, but those includes are handled as "config fragments". All the relative paths in the included file are relative to the `dobi.yaml` which **includes** the file.

In a subproject setup, the paths need to be adjusted so that they are relative to the directory of the file that references them.

I'd like to support both use cases. 

My proposal is to add a new field to `meta:` called `subproject:` which would act like `includes:` but would handle rewriting all the "known" paths to be relative to file which references them. The fields which include known paths are:
* `image.context`
* `job.artifact`
* `job.sources`
* `mount.bind`
* `compose.files`
* `meta.include`
* `meta.subproject`

Other paths (like `image.dockerfile`, `job.command`, etc) are already relative to a context directory, so don't need to be modified.

**Comment by deinspanjer** [comment]
This sounds promising.  Do you think that the subproject should still be able to be run from within that directory as well as from the parent? Would it still have access to the parent's resources?

**Comment by dnephin** [comment]
Good questions. I think it should be able to run from within the project directory, that would be the major reason to create a separate thing from `includes` which are not meant to run on their own.

I think that raises another question, which is, should subproject dobi files be allowed to include a `meta.project` and `meta.default`. Right now those are not allowed in included files. I'm thinking they should be allowed.

> Would it still have access to the parent's resources?

I don't think it would, no. It would have to be able to run self-contained if it were run directly.

**Comment by dnephin** [comment]
Another possible implementation would be to make includes an object instead of just a string. That would let us include other parameters like `optional:` on the includes:

```yaml

meta:
  includes:
    - path: subproject_a/dobi.yaml
      update-relative-paths: true
    - path: dobi-local.yaml
      optional: true
```

**Comment by dnephin** [comment]
Another idea from https://github.com/dnephin/dobi/issues/40#issuecomment-255088427 would be to support remote http urls as the include path.

`dobi` would download the file and cache it in `.dobi/includes/<url>`. Each time `dobi` is run it could use the locally cached copy of the config to include tasks that are common between projects.

**Comment by dnephin** [comment]
Maybe the `include` field could be either:
* a list of filepaths (strings) which use the existing include logic ("fragment" style includes)
* a list of objects with the structure:

```yaml
file: ./path
path-relativity: {file | project}
optional: true
```

or 

```yaml
url: 'http://...'
cache: { once | always | <duration> }
```

`path-relativity` sets how paths in the included files are interpreted. `project` would be the current behaviour, and `file` would make them relative to the file which contains the paths.

`optional: true` makes it so that if a file is missing it's not an error, and will be skipped.

The `url` type include would let you include a recipe from some url (http for now, maybe git later). `cache` lets you set how long to cache the downloaded recipe.

**Comment by deinspanjer** [comment]
I believe this approach would make it straightforward to have a sequence of build files that could either work on a specific sub-project or on the entire parent project as necessary.

**Comment by cescoferraro** [comment]
@dnephin I think the url is just the case of a file that is not on the local disk. 
we just need to check whenever base-path is a url with things like
https://godoc.org/github.com/goware/urlx#Parse
We could also make file optional so dobi would include all yaml files within base-path

```yaml
file: './dobi.yaml'  | 'blob/master/dobi.yaml' | 'raw/8707e690327ac7113117d6f197a4d51fddf5ed66/.bash.local'
optional: true
cache: { once | always | <duration> } 
base-path: {'/usr/dobi/mars-project ' | 'http://github.com/cescoferraro/mars-project' | 'https://gist.github.com/cescoferraro/7fd60083f4f31655d3015d6d959938f5' }  
```

We should also make file optional so dobi would include all yaml files within base-path.
So we could do something like

```yaml
includes:
  -  base-path: {'http://github.com/dobi/dobi-templates/blob/master/golang'}  
     cache: { once } 
  -  base-path: {'http://github.com/xxx/yet-another-dobi-templates/blob/master/react'}  
     cache: { once } 
```
