### ISSUE TITLE
Versioning Golang app

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#35]
The dobi repo itself holds its version inside cmd/dobi.go just like most go apps.
How can I use that specific version as an environment variable so I can push images accordingly.
With a Makefile is quite easy.

```
export VERSION:=$(shell go run src/backend/api.go version)

deploy:
	@echo Building version $(VERSION)
    docker-compose push production
    ...
```

I want to avoid setting it manually like VERSION=0.1.4 dobi production:push
```
job=binary:
    use: builder
    artifact: dist/
    mounts: [source,dist]
    command: go install src/backend/api.go
    working-dir: /go/src/bitbucket.org/cescoferraro/api
    description: "Build the static binary"

image=production:
    image: cescoferraro/api
    tags: ["v{env.VERSION}"]
    dockerfile: docker/Dockerfile.prod
    depends: [binary]
    description: "Production Image"
```

**Comment by dnephin** [comment]
I think #9 is what you need. It would let you run a job and capture the stdout to inject as an environment variable.

**Comment by cescoferraro** [comment]
Just merged it and tested with
```
meta:
    project: dobi
    default: all


image=go:
    image: golang-1.7.1
    context: .

job=calculate-version:
  use: go
  command: go version

env=dev-settings:
  captures:
    - job: calculate-version
      variable: version

job=test:
  use: go
  command: echo $VERSION
  env:
    - VERSION={env.version}
```
And got:


```
Error at dev-settings: missing dependencies:
```

**Comment by dnephin** [comment]
Oh yes, it's not quite ready yet.It still needs a bit of work

**Comment by dnephin** [comment]
I took a bit of a different route, but this is now implemented.  The `env` resource is already merged, and #50 adds support for capturing output of a job.

Using the example above, you could do:

```yaml

image=go:
  image: golang
  tags: [1.7.1-alpine]
  pull: once

job=calculate-version:
  use: go
  command: go version

job=echo:
  use: go
  command: 'sh -c "echo $VERSION"'
  env: ['VERSION={env.VERSION}']
  depends: ['calculate-version:capture(VERSION)']

```
