### ISSUE TITLE
VCS Integration

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#40]
Hello!
Just pushed this WIP PR #39. Mainly to talk about how can dobi better integrate with git.

As I see things, there are two flows I would like dobi to allow. The first one is what #39 aims to achive.
Forbidding a job to run if  HEAD  is not the same as the dobi job branch parameter. This would allow a workflow similar to the below.
- Its not quite clear in my mind yet if we need to provide similar behavior with the image resource. Since if a image depends on a job that is bound to a branch, the image task would not run anyway.

```
job=release:
    use: releaser
    mounts: [dist]
    branch: "master"
    env:
     - "VERSION={env.VERSION}"
    depends: [binary]

job=canary:
    use: releaser
    branch: "canary"
    env:
     - "VERSION={env.CANARY_VERSION}"
    depends: [binary]
```

The second would allow a workflow similar to [Captain](https://github.com/harbur/captain) where `dobi build`,`dobi push` and `dobi pull` would run/push/pull a specific image task depending where HEAD is. This would be great as a base for a future deploy resource. Maybe a git resource that would let the user link branch to an image

```
git:
    branches:
     - canary=canary
     - master=release
```

**Comment by dnephin** [comment]
So far the only integration is through variables. You can get git branch from '{git.branch}`, which can be passed to the job from an environment variable. From inside the job you could then check the branch and `exit 1` if it doesn't match the expected.

What's the use case for not allowing a job to run instead of just paramaterizing the job to run with the branch name?

**Comment by cescoferraro** [comment]
@dnephin 

Paramaterizing a job to specific branch would narrow the workflow possibilities. 
I use git-flow so all features fall under "features/****".  
I might want a canary job to be able to run on any feature/** branch.
But at the same time would like to make sure the release job only run on master

**Comment by dnephin** [comment]
My big concern with more integration with VCS is that it makes it a lot more work to add support for new ones. If the only support is variable it will  be easy to add feature parity for others.

If there is tight integration where `dobi` is actually aware of things like tags and branches it becomes a lot more work to support another VCS, and could add a lot of complication if the objects don't map cleanly to each other (ex: doesn't have the same concept for tags or branches).

Since these restrictions can be imposed from inside a job by passing in the variable to the job, it seems like you could do what you want today with a script in the container, right?

**Comment by cescoferraro** [comment]
If .git is mounted inside the container, I can script anything. But in this scenario, dobi would spin the container anyway just to figure out it shouldnt have ran.

**Comment by dnephin** [comment]
That's true, but this scenario should be pretty rare, right? It's only to catch an accidental run when you're on the wrong branch? Or do you expect it to happen often?

**Comment by cescoferraro** [comment]
Accidental things seem to happen a lot with those around me, myself included. Its the only motive.
The approach would also compromise the the subsequent task because they might expect the previous job to have accomplished something. I also do not want dobi to be tightly integrated with git but I see this more like a health check feature just to ensure a successful dobi run is truly successful

**Comment by cescoferraro** [comment]
@dnephin  github.com/Masterminds/vcs seems like a cool cross vcs package

**Comment by dnephin** [comment]
That does look really cool, we use their `glide` too for deps as well

**Comment by dnephin** [comment]
> The script approach would also compromise the the subsequent task because they might expect the previous job to have accomplished something. 

As long as the check exits with a non-zero code, none of the following tasks will execute, so i think this is ok.

It could even be done with a single image that is shared between projects:

```yaml

image=branch-checker:
  image: cescoferro/branch-checker
  tags: [latest]
  pull: once

job=check-branch-is-master:
  use: branch-checker
  env:
    - 'ACTIVE_BRANCH={git.branch}'
    - 'ALLOW_BRANCHES=master'

job=release:
  ...
  depends: [check-branch-is-master]
```

Since the branch-checker would exit with status code 1, the release would never run. You don't even have to modify the release script, it can all be done from a generic image/job.

It could even be moved out into a separate yaml, and just included with `meta.include`

**Comment by cescoferraro** [comment]
I like this approach better! But still looks like a lot of boilerplate. It would force the user to maintain an docker image that would just run `[[ ${ACTIVE_BRANCH} == ${ALLOW_BRANCHES} ]]`.

IMHO dobi should handle those normal use cases. Maybe we could add a recipe metadata field, that would allow us to include the resources needed by these workflow programativally with an images we can maintain. I can see a lot of others usefull recipes we could agregate, making dobi easier to use as well as keeping the config file as slim as possible

**Comment by dnephin** [comment]
True, I guess this could be improved even further to something like this:

```yaml
image=branch-checker:
  image: bash
  tags: [latest]
  pull: once

job=check-branch-is-master:
  use: branch-checker
  command: 'bash -c \'[[ ${ACTIVE_BRANCH} == "master" ]]\''
  env: ['ACTIVE_BRANCH={git.branch}']

job=release:
  ...
  depends: [check-branch-is-master]
```

The recipes idea is really interesting. Right now the only support is `include: ...` and #22 looks at expanding the support of `include: ...`.  Maybe another include type could be a remote http url? 

That way you could host recipes in some common place, and dobi would download and cache the config the first time you run it. Do you think that would work for recipes?
