### ISSUE TITLE
Mount Devices 

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#43]
Trying to mount an arduino to a container runned by dobi Fails

```
mount=device:
    bind: /dev/ttyACM0
    path: /dev/ttyACM0

job=watch:
    use: watch-builder
    interactive: true
    net-mode: host
    ports: ["5000:5000"]
    mounts: [source,machine-id,device]
    env:
      - "POWER_JWT={env.POWER_JWT:}"
    description: "Watch for code changes and run the unit tests"
```

The same container created by dobi, run with plain docker using the --device flag:

```
cesco@cesco-desktop: ~/code/go/src/github.com/cescoferraro/power on master [+!?]
$ docker run -p 5000:5000 -v /var/lib/dbus/machine-id:/var/lib/dbus/machine-id  -v $PWD:/go/src/github.com/cescoferraro/power --device /dev/ttyACM0 --net=host  cescoferraro/power:watch 
[00] Starting service
[00] 2016/10/22 00:38:52 Failed to read config Unsupported Config Type ""
[00] 2016/10/22 00:38:52 verbose enabled
[00] 2016/10/22 00:38:52 ***********VIPER*************
[00] 2016/10/22 00:38:52 ping: true
[00] 2016/10/22 00:38:52 channels: 8
[00] 2016/10/22 00:38:52 owner: francescoaferraro@gmail.com
[00] 2016/10/22 00:38:52 api: https://api.cescoferraro.xyz/iot/devices
[00] 2016/10/22 00:38:52 dev-api: http://localhost:9000/iot/devices
[00] 2016/10/22 00:38:52 serial_port: /dev/ttyACM0
```

I am trying to set a single device on job/run.go and it works like this. I was wondering how should we implement this. ["host:container:cgroup"] or  ["same:cgroup"] or ["same"] with full permissions?

```
job=binary:
    use: builder
    artifact: ./dist/bin/
    devices: "/dev/ttyACM0"


	device := docker.Device{
		PathInContainer:t.config.Devices,
		PathOnHost:t.config.Devices,
		CgroupPermissions:"rwm"}

	portBinds, exposedPorts := asPortBindings(t.config.Ports)
	// TODO: only set Tty if running in a tty
	opts := docker.CreateContainerOptions{
		Name: name,
		Config: &docker.Config{
			Cmd:          t.config.Command.Value(),
			Image:        imageName,
			User:         t.config.User,
			OpenStdin:    interactive,
			Tty:          interactive,
			AttachStdin:  interactive,
			StdinOnce:    interactive,
			AttachStderr: true,
			AttachStdout: true,
			Env:          t.config.Env,
			Entrypoint:   t.config.Entrypoint.Value(),
			WorkingDir:   t.config.WorkingDir,
			ExposedPorts: exposedPorts,
		},
		HostConfig: &docker.HostConfig{
			Binds:        t.bindMounts(ctx),
			Privileged:   t.config.Privileged,
			NetworkMode:  t.config.NetMode,
			Devices:  []docker.Device{device},
			PortBindings: portBinds,
		},
	}

```

**Comment by dnephin** [comment]
We can probably re-use the docker code to parse this microformat. The code is here:
https://github.com/docker/docker/blob/064eda192e945f70c405ce537ad9f8843fb9205b/runconfig/opts/parse.go#L768-L801

Sometimes trying to vendor docker/docker causes some dependency issues, so if that doesn't work maybe just emulate that code for now?

**Comment by dnephin** [comment]
Actually, maybe we should avoid using the microformat, and instead use a full struct:

```yaml
job=binary:
  ...
  devices:
    - host: /dev/ttyACM0
      container: /dev/ttyACM0
      permissions: rwm
```
