### ISSUE TITLE
env var on a job command

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#53]
maybe I am missing a way to skip those chars

```
image=busybox:
    image: busybox
    tags: ["latest"]
    pull: "once"

job=play:
    use: busybox
    interactive: true
    command: env
    depends: [production-vars]
    env:
      - "VERSION={env.VERSION}"
    description: "bla"


job=play:
    use: busybox
    interactive: true
    command: echo $VERSION
    depends: [production-vars]
    env:
      - "VERSION={env.VERSION}"
    description: "bla"
```

```
cescoferraro@desktop: ~/code/go/src/github.com/cescoferraro/api on develop [+!?$]
$ dobi play
[env:set production-vars] Done
[job: play] env Start
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1b44e5e5e282
TERM=xterm
VERSION=0.2.5
HOME=/root
[job: play] env Done
cescoferraro@desktop: ~/code/go/src/github.com/cescoferraro/api on develop [+!?$]
$ dobi play
[env:set production-vars] Done
[job: play] echo ${VERSION} Start
${VERSION}
[job: play] echo ${VERSION} Done
```
