### ISSUE TITLE
Job abstraction

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#58]
These are the current dobi's resources:

```
// Build tool specific
- env
- alias
// You are nice
- compose
// What the end user actually run/expects
- image 
- job
// you cant use a mount on a image. Its strictly job related
- mount
```

But images are a boring abstraction. Compose deals with them super nice already. You just run from a file or ou pull it from the hub. Its how you actually run them is what makes dobi special. We should make the job abstraction stronger for itself. I think that ultimately dobi should support a single manifest abstraction for running a job, in the same sense of #55, alowing the end user to have a single file with all the information about the job.

```
job=watch:
    image:  
        // I dont like this. currently `image=refactorer:    image: dnephin/go-refactor` is a stutterer
        // I would rather container, container-name or repo or name. IDK
        container: dnephin/dobi-dev  
        steps:
          - FROM: golang:1.7-alpine
          - RUN: apk add -U git bash curl tree
          - RUN: go get github.com/dnephin/filewatcher
          - GLIDE: 0.12.3
    command: filewatcher x '.git' -- go run main.go
    interactive: true
    working-dir: /go/src/github.com/dnephin/dobi
    description: "Watch for code changes and run"
    env:
      - 'PS1=# '
      - 'CGO_ENABLED=0'
    local-mounts:
        - bind: .
          path: /go/src/github.com/dnephin/dobi
```

The main intent here is to make dobi more concise, avoiding the file changing dizzyness as well as saving some lines from the dockerfile itself, once that we dont need to set things like WORKDIR and ENV because we enforced them on the way the job run. So when you are actually hands on writing a dobi resource, you either decide if you need a image or a job. You might use the other stuff, but only if you want/need. You would also be able to keep a 1:1 ratio of the tasks you will actually be able to run with the number of resource you wrote.

To do that we need to 
1. Implement local-mount field on a job, seem easy.
2. Implement a image field tha would embed a image type inside a job to run instead of use field, which sounds way trickier.
