### ISSUE TITLE
`image:push` to  private registries is broken when using hostname/repo

### ISSUE THREAD

**Issue by dnephin** [dnephin/dobi#6]
I believe you should be able to push to a private registry by using the full name of the image that includes the host/port/path to the registry.  

`dobi` supports the same auth config as the docker client, so authentication should work as well.

I need to test it out to confirm.

cc @jmmills (let's move the discussion here, out of https://github.com/docker/compose/issues/1126)

**Comment by jmmills** [comment]
Personally I think it would be most useful as a parameter that can be carried into the build via environment variable.

I've always been a bit dissatisfied having to include a hostname (of a registry host) in the namespace declaration of an image.

**Comment by dnephin** [comment]
I suppose if `image.image` supported [variables](http://dnephin.github.io/dobi/variables.html) you would be able to do something like:

```
image=myimage:
    image: '{env.registry:}user/myimage'
```

**Comment by tedstirm** [comment]
That or if there was some way in the tags field to access the image name so you could do something like:
```
tags:
   - '{env.registry}/{image.name}'
```
I would like to be able to tag an image locally with a name, then prepend the private registry it belongs to later via an alias command that applies all my tags.

**Comment by dnephin** [comment]
Right now `tags` are only the "tag" part of the image name, so `latest`, `3.2`, etc. It seems like it would be a reasonable addition to allow these to be full `name:tag` strings as well. I think that would be good.

I'm not sure about `{image.name}`. The value would have to change per-resource, so the variable resolution would need to include that context. It's certainly possible, but it would add some complexity to it. For now it seems like it would be best to just repeat the name. If it becomes a common pattern it could be added.

**Comment by jzakrzeski** [comment]
I've actually been evaluating dobi to include as part of our CI pipeline with Docker containers, and this is a big need. I've attempted a setup like this for a ruby app I maintain:
```
meta:
  project: cattle-prod

# Mounts #

mount=source:
  bind: ./cattle-prod
  path: /code
  description: "source code directory"

mount=project:
  bind: .
  path: '{fs.projectdir}'
  description: "root project directory"

# Images #

image=cattle-prod:
  image: my.private.registry.net/cattle-prod
  context: ./cattle-prod
  tags: ['{git.short-sha}']
  dockerfile: Dockerfile
  description: "image to be used for testing/development"
```
Running `dobi cattle-prod:push` always falls back to trying to push to the hub despite having named the image as I would normally doing `docker push`. It does handle the tagging (and tests) very nicely, but I'd prefer to be able to go end-to-end with it so I can define jobs in the git repository instead of having to manually manage jenkins jobs per git repo.

Here's what I get using dobi with this project:
```
[DEBUG] Using default registry "https://index.docker.io/v1/"
[WARN] Missing auth config for "https://index.docker.io/v1/"
The push refers to a repository [my.private.registry.net/cattle-prod]
```
I've tried some thing like setting mounts as `depends:` for the image that include my `~/.docker` directory mapped (which has the auths for that registry cached), but to no avail--still times-out trying to push to the hub rather than my registry, though it is seen. Granted, I've been looking at this solidly for the past hour so I could just be missing something obvious unless dobi does, indeed, not support this properly.
