### ISSUE TITLE
Add "env" resource

### ISSUE THREAD

**Issue by dnephin** [dnephin/dobi#9]
An `env` resource is a list of environment variables. 

By itself it doesn't do much, but as a step in an alias, it can be used to fulfill variables required by build steps later in the list. That would allow for a single build step to work differently based on the `env` resource that appears before it in the alias task list.

Possibly also allow reading values from a file.

How is this going to work with resolving variables at config time?

**Comment by deinspanjer** [comment]
Is this the list of the variable names that would be pulled out of the environment or the actual values that would be injected into the environment?

**Comment by dnephin** [comment]
Good question, I think the list would be the key=value pairs. Values can be injected from the shell environment by using the standard [config variables](http://dnephin.github.io/dobi/variables.html) 

```yaml

env=dev-settings:
- "one=hardcodedvalue"
- "two={env.two}"

```

**Comment by deinspanjer** [comment]
Gotcha.  I figured that was the gist, but I'm wondering how it plays with the "project setup" example you provided.

Maybe this feature would provide the canonical defaults but you would still use something like that setup task to prompt for overrides?

**Comment by dnephin** [comment]
If this resource supported loading the environment key=value pairs from a file, the project setup example could be used to initialise that file.

I was thinking the primary use for this resource would be to have a single job with environment parameters, and aliases that allow you to run the job with different env variables:

```yaml

env=dev-env:
  - host=dev.project
  - port=3800
  - debug=true

env=stage-env:
  - host=stage.project
  - port=80

job=start-service:
  use: service-img
  env:
    - HOST={env.host}
    - PORT={env.port}
    - DEBUG={env.debug:}


alias=run-dev:
  tasks: [dev-env, start-service]

alias=run-stage:
  tasks: [stage-env, start-service]
```

The `{env....}` variables in the job would be satisfied by the environment resource.  

However, this would require a change to how variable resolving is done. Maybe there is an easier way to inject the variables into the job resource. I would still like to make it explicit which variables are being set.

**Comment by dnephin** [comment]
Another use case for this resource type could be loading values from the execution of some `job`. 

Maybe the `env` resource could have a `capture: <jobname>` field. Where it runs a job and captures the stdout as a variable.

The full definition might look something like this:

```yaml

job=calvulate-version:
  use: bash
  command: ...

env=dev-env:
  files: [dev.env, local.env]
  variables:
    - host=dev.project
    - port=3800
  capture: 
    - version=calculate-version

```

**Comment by dnephin** [comment]
WIP branch: https://github.com/dnephin/dobi/tree/add-env-resource

**Comment by OnkelTem** [comment]
I don't really understand how to use this.

Let's consider the most trivial task - configuring job with some defaults allowing for overriding.

## Dreams

This is how I imagine it may work:
**dobi.yaml**
```
job=import:
    # ...
    env:
        - PGHOST=db
        - PGUSER=postgres
        - PG_WORK_MEM
        - PG_MAINTENANCE_WORK_MEM
    env-files: [import.ignored.env]
```
Now I can optionally override some variables in **import.ignored.env**:
```
PG_WORK_MEM=100MB
```
having it ignored by `.gitignore`. And it's done.

## Real life

There is no `env-files` option of `job` resources but there is `env` resource.

### Attempt 1

**dobi.yaml**
```
job=import:
    # ...
    env:
        - PGHOST=db
        - PGUSER=postgres
        - PG_WORK_MEM
        - PG_MAINTENANCE_WORK_MEM
    depends: [e-import]

job=e-import
    files: [import.ignored.env]
```
This doesn't work, as the file must exist for some reason. So I can't provide a list of optional overrides: `[this.env, that.env, that.overrides.env]`.

### Attempt 2

Then probably I can move my variables to that file? Ok, let's create this file which is not must be a part of git repository without possibility to override it:

**import.env**
```
PGHOST=db
PGUSER=postgres
PG_WORK_MEM
PG_MAINTENANCE_WORK_MEM
```
**dobi.yaml**
```
job=import:
    # ...
    depends: [e-import]

job=e-import
    files: [import.env]
```
But no: job doesn't read variables at all and they all are just missing.

### Attempt 3

So it seems like I have to repeat each and every variable now, and substitute them one by one:
**dobi.yaml**
```
job=import:
    # ...
    env:
        - PGHOST={env.PGHOST}
        - PGUSER={env.PGUSER}
        - PG_WORK_MEM={env.PG_WORK_MEM}
        - PG_MAINTENANCE_WORK_MEM={env.PG_MAINTENANCE_WORK_MEM}
    depends: [e-import]

job=e-import
    files: [import.env]
```
**import.env**
```
PGHOST=db
PGUSER=postgres
PG_WORK_MEM
PG_MAINTENANCE_WORK_MEM
```
And this doesn't work one more damned time. Now the reason is that I have `PG_WORK_MEM` and `PG_MAINTENANCE_WORK_MEM` empty and why dobi cares about what it's not definitely its business I don't know.

### Attempt 4
Out of interest I also tried to see how `variables` work in `env` resource and I've discovered that despite  it's documented as being a list of `key=value` pairs (just like `env` of jobs), it doesn't actually allow you to declare: `[VAR]`, it requires some value: `[VAR=]`.

So it is really usable? I can't think of use cases actually.
