### ISSUE TITLE
Add a stack resource

### ISSUE THREAD

**Issue by dnephin** [dnephin/dobi#92]
A stack resource would create/remove a Docker Stack.

```yaml

stack=devenv:
  name: dev
  files: [...]
  prune: true|false
  with-registry-auth: true|false
```

At the same time we should deprecate the compose resource, since it can be replaced by a stack resource.
